server:
  port: 8001
spring:
  application:
    name: eureka-server
  security:
    user:
      name: luke
      password: 123456
eureka:
  instance:
    hostname: luke-a
  client:
    serviceUrl:
      defaultZone: http://luke-b:8000/eureka/
    # fetch-registry: false
    register-with-eureka: true
  #server:
  #  enable-self-preservation: false
