server:
  port: 8001 #指定运行端口
spring:
  application:
    name: eureka-server #指定服务名称
  security: #配置SpringSecurity登录用户名和密码
    user:
      name: luke
      password: 123456
eureka:
  instance:
    hostname: luke-a #指定主机地址
  client:
    serviceUrl:
      defaultZone: http://luke-b:8000/eureka/ #注册到另一个Eureka注册中心
    # fetch-registry: false #指定是否要从注册中心获取服务（单机时 注册中心不需要开启）
    register-with-eureka: true  #指定是否要注册到注册中心（单机时 注册中心不需要开启）
  #server:
  #  enable-self-preservation: false #关闭保护模式
